# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isVote',
            field=models.BooleanField(default=True),
        ),
    ]
