# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 15:43
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_isvote'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
